module.exports = {
    COMMUNITY_CHAT: "COMMUNITY_CHAT",
    USER_CONNECTED: "USER_CONNECTED",
    MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
    MESSAGE_SENT: "MESSAGE_SENT",
    USER_DISCONNECTED: "USER_DISCONNECTED",
    TYPING: "TYPING",
    VERIFY_USER: "VERIFY_USER",
    LOGOUT: "LOGOUT",
    PRIVATE_MESSAGE: "PRIVATE_MESSAGE",
    NOTIFY_REQUEST_MESSAGE: "NOTIFY_REQUEST_MESSAGE",
    NOTIFY_REQUEST_PRIVATE_MESSAGE: "NOTIFY_REQUEST_PRIVATE_MESSAGE",
    REGISTER_USER: "REGISTER_USER",
    FRIEND_REQUEST: "FRIEND_REQUEST"
};
